#### In This notebook I am showing How can you save your model to a file

In [14]:
## Importing libraries
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import warnings
warnings.filterwarnings('ignore')

In [2]:
## loading dataset
df = pd.read_csv('house-pricing.csv')
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    5 non-null      int64
 1   price   5 non-null      int64
dtypes: int64(2)
memory usage: 208.0 bytes


In [10]:
## In this notebook I am showing only how to save so iam skipping EDA Train Test split etc
X = df[['area']]
y = df['price']

In [9]:
y

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [11]:
## Model Training
regression = LinearRegression()
regression.fit(X,y)

LinearRegression()

In [15]:
# predicting 
regression.predict([[2000]])

array([452191.78082192])

In [21]:
regression.predict([[4500]])

array([791660.95890411])

### Saving model using " PICKLE " method

In [17]:
import pickle

# saving model
with open ('pickle_model','wb') as file:
    pickle.dump(regression,file)


In [18]:
# loading model

with open ('pickle_model','rb') as file:
    lin_reg = pickle.load(file)

In [19]:
## predicting 
lin_reg.predict([[2000]])

array([452191.78082192])

In [20]:
lin_reg.predict([[4500]])

array([791660.95890411])

here in these two examples we got same answer